name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add grammar versions you have implemented (e.g. [1, 2, 3, 4, 5])
        grammar: [1]
        stage: ["lexer"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test harness dependency
        run: pip install pytest

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v2
        with:
          version: latest
          platform: x64

      - name: Build compiler
        run: make

      - name: Run tests for grammar ${{ matrix.grammar }}
        run: python3 test/run_tests.py test --stage ${{matrix.stage}} --grammar ${{ matrix.grammar }} --no-build